# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara/rails'
require 'rack_session_access/capybara'

# Use Minitest assertions instead of RSpec expectations
require 'minitest/assertions'
World(Minitest::Assertions)

# Configure Capybara
Capybara.default_driver = :rack_test
Capybara.javascript_driver = :selenium_chrome_headless

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Disable Cucumber's built-in database cleaner to avoid conflicts
Cucumber::Rails::Database.autorun_database_cleaner = false

# Use truncation strategy for database cleaning due to PostgreSQL FK constraints
# and Supabase integration
begin
  DatabaseCleaner.strategy = :truncation, { except: %w[ar_internal_metadata schema_migrations] }
rescue NameError
  raise 'You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it.'
end

# Drop problematic FK constraints that don't match the Rails models
# These FKs reference the wrong primary keys due to schema.rb issues
Before do
  DatabaseCleaner.start

  # Drop FK constraints that reference wrong columns
  # org_roles.org_id should reference organizations.org_id, not organizations.id
  # org_roles.user_id should reference user_data.user_id
  # user_data.user_id should reference auth.users which doesn't exist in test
  ActiveRecord::Base.connection.execute(<<~SQL)
    ALTER TABLE org_roles DROP CONSTRAINT IF EXISTS fk_rails_978ab3298a;
    ALTER TABLE org_roles DROP CONSTRAINT IF EXISTS fk_rails_7248ee8404;
    ALTER TABLE user_data DROP CONSTRAINT IF EXISTS fk_user_data_auth_users;
  SQL
end

After do
  DatabaseCleaner.clean
  Capybara.reset_sessions!
end

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation
