plugins:
  - rubocop-erb

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# Basic cops only
Layout/LineLength:
  Max: 120
  Exclude:
    - "db/seeds.rb"
    - "db/schema.rb"
    - "db/migrate/**/*"

Lint/UselessAssignment:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
