post:
  summary: Recreate a past order
  parameters:
    - name: org_id
      in: path
      required: true
      schema:
        type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../../components/schemas/OrderRecreate.yaml"
  responses:
    "201":
      description: Order recreated
      content:
        application/json:
          schema:
            $ref: "../../../components/schemas/Message.yaml"
          example:
            message: order recreated
  tags:
    - Prepping for Club Event
  operationId: _orgs_org_id_inventory_order_post
  description: POST operation for /orgs/{org_id}/inventory/order.
