openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "CheckMate API"

servers:
  - url: https://www.checkmate.com/api/v1

components:
  schemas:
    UserLogin: { $ref: "./components/schemas/UserLogin.yaml" }
    UserData: { $ref: "./components/schemas/User.yaml" }
    ItemDetails: { $ref: "./components/schemas/ItemDetails.yaml" }
    Items: { $ref: "./components/schemas/Items.yaml" }
    OrderDetails: { $ref: "./components/schemas/OrderDetails.yaml" }
    Orders: { $ref: "./components/schemas/Orders.yaml" }
    Organizations: { $ref: "./components/schemas/Organizations.yaml" }
    OrgLogs: { $ref: "./components/schemas/OrgLogs.yaml" }
    OrgRoles: { $ref: "./components/schemas/OrgRoles.yaml" }
    Returns: { $ref: "./components/schemas/Returns.yaml" }
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []

paths:
  /users/{id}:
    $ref: "./paths/users/{id}.yaml"
